# Generated by Django 4.1.7 on 2023-03-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managefee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('JANVIER', 'janvier'), ('FEVRIER', 'fevrier'), ('MARS', 'mars'), ('AVRIL', 'avril'), ('MAI', 'mai'), ('JUIN', 'juin'), ('JUILLET', 'juillet'), ('AOUT', 'aout'), ('SEPTEMBRE', 'septembre'), ('OCTOBRE', 'octobre'), ('NOVEMBRE', 'novembre'), ('DECEMBRE', 'decembre')], max_length=20),
        ),
    ]
