# Generated by Django 4.1.7 on 2023-03-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managefee', '0004_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
