# Generated by Django 4.1.7 on 2023-03-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managefee', '0005_alter_fee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='date',
            field=models.DateField(),
        ),
    ]
