# Generated by Django 4.1.7 on 2023-04-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managefee', '0006_alter_fee_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
    ]
