# Generated by Django 4.1.7 on 2023-04-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managefee', '0007_remove_subscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
    ]
