# Generated by Django 4.1.7 on 2023-03-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='feecharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
