# Generated by Django 5.1.4 on 2024-12-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bloc',
            field=models.CharField(choices=[('b1', 'B1'), ('b2', 'B2'), ('b3', 'B3'), ('b4', 'B4'), ('b5', 'B5'), ('b6', 'B6'), ('b7', 'B7'), ('b8', 'B8'), ('b9', 'B9'), ('b10', 'B10')], default='b1', max_length=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
